from google.colab import drive
drive.mount('/content/drive')

In [ ]:

from google.colab import files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Dependencies and Setup
import pandas as pd
import numpy as np


# File to Load (Remember to Change These)
#from google.colab import files
#uploaded = files.upload()



# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv('/content/drive/MyDrive/schools_complete.csv')
student_data = pd.read_csv('/content/drive/MyDrive/students_complete.csv')

# Combine the data into a single dataset.
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_data_complete.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

## District Summary

In [ ]:
# Calculate the total number of unique schools(ie how many distinct schools are in the school_name column)
school_count = school_data_complete['school_name'].nunique()# nunique() will count the distinct/unique schools in the column
print(school_count)

school_count = school_data_complete['school_name'].unique()# unique() shows all the different schools leaving you to cal the individual nos urself
school_count = len(school_data_complete['school_name'].unique())# The len() narrows it down to distinct nos
#print(school_count)
school_count

15

15

In [ ]:
# Calculate the total number of students
student_count = (school_data_complete['student_name'].count()) # The count function is used for strings or to count occurances while sum is used to summarize a numerical data
print(student_count)
#or
student_count = len(school_data_complete['student_name'])
print(student_count)
student_count

39170
39170

39170

In [ ]:
# Calculate the total budget
total_budget = school_data['budget'].sum()
print(total_budget)

24649428

In [ ]:
# Calculate the average (mean) math score
average_math_score = school_data_complete['math_score'].mean()# here i used the mean() to get direct result
print(average_math_score)
# OR
average_math_score = school_data_complete['math_score'].sum() / len(school_data_complete['math_score'])
print(average_math_score)# Here i got the sum first and divided by the length(total row no)in column(math score)

78.98537145774827
78.98537145774827

In [ ]:
# Calculate the average (mean) reading score
average_reading_score = school_data_complete['reading_score'].mean()
# OR
average_reading_score = school_data_complete['reading_score'].sum() / len(school_data_complete['reading_score'])
print(average_reading_score)

81.87784018381414

In [ ]:
# Use the following to calculate the percentage of students who passed math (math scores greather than or equal to 70)
passing_math_count = school_data_complete[student_data["math_score"] >= 70]["student_name"].count()
passing_math_percentage = passing_math_count / (student_count) * 100
print(passing_math_percentage)
#Or
passing_math_count = len(school_data_complete[student_data["math_score"] >= 70]["student_name"])
passing_math_percentage = passing_math_count / float(student_count) * 100
print(passing_math_percentage)

74.9808526933878
74.9808526933878

In [ ]:
# Calculate the percentage of students who passed reading (hint: look at how the math percentage was calculated)
passing_reading_count =school_data_complete[student_data['reading_score'] >= 70]['student_name'].count()
passing_reading_percentage = passing_reading_count / (student_count) * 100
print(passing_reading_percentage)

85.80546336482001

In [ ]:
# Use the following to calculate the percentage of students that passed math and reading
passing_math_reading_count = school_data_complete[
    (school_data_complete["math_score"] >= 70) & (school_data_complete["reading_score"] >= 70)].count()["student_name"]
overall_passing_rate = passing_math_reading_count /  float(student_count) * 100
overall_passing_rate
# Or
passed_students = school_data_complete[(student_data['reading_score']>=70) & (student_data ['math_score'] >=70)]['student_name'].count()
percentage = passed_students / (student_count) * 100
print(percentage)

65.17232575950983

In [ ]:
# Create a high-level snapshot of the district's key metrics in a DataFrame: Summarrize important data point or performance indicators
district_summary = pd.DataFrame({
    "Total Schools": [school_count],
    "Total Students": [student_count],
    "Total Budget": [total_budget],
    "Average Math Score": [average_math_score],
    "Average Reading Score": [average_reading_score],
    "% Passing Math": [passing_math_percentage],
    "% Passing Reading": [passing_reading_percentage],
"% Overall Passing": [overall_passing_rate]
})
#district_summary = district_summary.transpose()
print(district_summary)

# Formatting
district_summary["Total Students"] = district_summary["Total Students"].map(" {:,}".format)
district_summary["Total Budget"] = district_summary["Total Budget"].map("${:,.2f}".format)
district_summary ["% Passing Math"] = district_summary["% Passing Math"].map("{:,.5f} %". format)
district_summary ["% Passing Reading"] = district_summary["% Passing Reading"].map(" {:,.5f} %". format)
district_summary ["% Overall Passing"] = district_summary["% Overall Passing"].map(" {:,.5f} %". format)
#Display the DataFrame
district_summary

   Total Schools  Total Students  Total Budget  Average Math Score  \
0             15           39170      24649428           78.985371

   Average Reading Score  % Passing Math  % Passing Reading  % Overall Passing
0               81.87784       74.980853          85.805463          65.172326

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,"39,170","$24,649,428.00",78.985371,81.87784,74.98085 %,85.80546 %,65.17233 %

## School Summary

In [ ]:
# Use the code provided to select all of the school types
school_names = np.array(school_data["school_name"].sort_values().unique())
print(school_names)

['Bailey High School' 'Cabrera High School' 'Figueroa High School'
 'Ford High School' 'Griffin High School' 'Hernandez High School'
 'Holden High School' 'Huang High School' 'Johnson High School'
 'Pena High School' 'Rodriguez High School' 'Shelton High School'
 'Thomas High School' 'Wilson High School' 'Wright High School']

In [ ]:
school_types = school_data.set_index(['school_name'])['type'].sort_index()
print(school_types)

school_name
Bailey High School       District
Cabrera High School       Charter
Figueroa High School     District
Ford High School         District
Griffin High School       Charter
Hernandez High School    District
Holden High School        Charter
Huang High School        District
Johnson High School      District
Pena High School          Charter
Rodriguez High School    District
Shelton High School       Charter
Thomas High School        Charter
Wilson High School        Charter
Wright High School        Charter
Name: type, dtype: object

In [ ]:
# Calculate the total student count per school
per_school_counts = school_data_complete['school_name'].value_counts().sort_index()
print(per_school_counts)

school_name
Bailey High School       4976
Cabrera High School      1858
Figueroa High School     2949
Ford High School         2739
Griffin High School      1468
Hernandez High School    4635
Holden High School        427
Huang High School        2917
Johnson High School      4761
Pena High School          962
Rodriguez High School    3999
Shelton High School      1761
Thomas High School       1635
Wilson High School       2283
Wright High School       1800
Name: count, dtype: int64

In [ ]:
# Calculate the total school budget and per capita spending per school
per_school_budget =school_data_complete['budget'].sum()
print(per_school_budget)
per_school_capita = total_budget / student_count
print(per_school_capita) # This refers to the average amount of money spent per student

82932329558
629.2935409752362

In [ ]:
# Calculate the average test scores per school
per_school_math = school_data_complete.groupby('school_name')['math_score'].mean()
print(per_school_math)

#per_school_reading =school_data_complete.groupby('school_name')['reading_score'].mean()
#print(per_school_reading)

school_name
Bailey High School       77.048432
Cabrera High School      83.061895
Figueroa High School     76.711767
Ford High School         77.102592
Griffin High School      83.351499
Hernandez High School    77.289752
Holden High School       83.803279
Huang High School        76.629414
Johnson High School      77.072464
Pena High School         83.839917
Rodriguez High School    76.842711
Shelton High School      83.359455
Thomas High School       83.418349
Wilson High School       83.274201
Wright High School       83.682222
Name: math_score, dtype: float64

In [ ]:
# Calculate the number of students per school with math scores of 70 or higher
students_passing_math = school_data_complete[pd.to_numeric(school_data_complete['math_score']) >= 70] ['student_name'].count()
print(students_passing_math)

29370

In [ ]:
# Calculate the number of students per school with reading scores of 70 or higher
students_passing_reading =school_data_complete[pd.to_numeric(school_data_complete['reading_score']) >= 70]['student_name'].count()
print(students_passing_reading)

33610

In [ ]:
# Use the provided code to calculate the number of students per school that passed both math and reading with scores of 70 or higher
students_passing_math_and_reading = school_data_complete[
    (school_data_complete["reading_score"] >= 70) & (school_data_complete["math_score"] >= 70)
]
school_students_passing_math_and_reading = students_passing_math_and_reading.groupby(["school_name"]).size()
print(school_students_passing_math_and_reading)

school_name
Bailey High School       2719
Cabrera High School      1697
Figueroa High School     1569
Ford High School         1487
Griffin High School      1330
Hernandez High School    2481
Holden High School        381
Huang High School        1561
Johnson High School      2549
Pena High School          871
Rodriguez High School    2119
Shelton High School      1583
Thomas High School       1487
Wilson High School       2068
Wright High School       1626
dtype: int64

In [ ]:
# Use the provided code to calculate the passing rates
#per_school_passing_math = students_passing_math / per_school_counts * 100
#per_school_passing_reading = students_passing_reading / per_school_counts * 100
#overall_passing_rate = students_passing_math + students_passing_reading / per_school_counts * 100
overall_passing_rate = (school_students_passing_math_and_reading/per_school_counts * 100).map("{:.0f}%".format)
print(overall_passing_rate)

school_name
Bailey High School       55%
Cabrera High School      91%
Figueroa High School     53%
Ford High School         54%
Griffin High School      91%
Hernandez High School    54%
Holden High School       89%
Huang High School        54%
Johnson High School      54%
Pena High School         91%
Rodriguez High School    53%
Shelton High School      90%
Thomas High School       91%
Wilson High School       91%
Wright High School       90%
dtype: object

In [ ]:
# Create a DataFrame called `per_school_summary` with columns for the calculations above.
per_school_summary ={
    'school_types': school_types,

    'Total Students': per_school_counts,
    'Total School Budget': per_school_budget,
    'Per Student Budget': per_school_capita,
    'Average Math Score': average_math_score,
    'Average Reading Score': average_reading_score,
    '% Passing Math': students_passing_math,
    '% Passing Reading': students_passing_reading,
    '% Overall Passing': overall_passing_rate

}

per_school_summary = pd.DataFrame(per_school_summary)


# Formatting
per_school_summary["Total School Budget"] = per_school_summary["Total School Budget"].map("${:,.2f}".format)
per_school_summary["Per Student Budget"] = per_school_summary["Per Student Budget"].map("${:,.2f}".format)
per_school_summary["% Passing Math"] = per_school_summary["% Passing Math"].map("{:.0f}%".format)
per_school_summary["% Passing Reading"] = per_school_summary["% Passing Reading"].map("{:.0f}%".format)


# Display the DataFrame
per_school_summary

,school_types,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Bailey High School,Bailey High School,4976,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,55%
Cabrera High School,Cabrera High School,1858,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Figueroa High School,Figueroa High School,2949,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,53%
Ford High School,Ford High School,2739,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,54%
Griffin High School,Griffin High School,1468,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Hernandez High School,Hernandez High School,4635,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,54%
Holden High School,Holden High School,427,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,89%
Huang High School,Huang High School,2917,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,54%
Johnson High School,Johnson High School,4761,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,54%
Pena High School,Pena High School,962,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Rodriguez High School,Rodriguez High School,3999,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,53%
Shelton High School,Shelton High School,1761,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,90%
Thomas High School,Thomas High School,1635,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Wilson High School,Wilson High School,2283,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Wright High School,Wright High School,1800,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,90%

## Highest-Performing Schools (by % Overall Passing)

In [ ]:
# Sort the schools by `% Overall Passing` in descending order and display the top 5 rows.
#merged_df = pd.merge(school_data_complete, per_school_summary, on='school_name')

top_schools = per_school_summary .sort_values(by = '% Overall Passing', ascending = False)
top_schools.head(5)

,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,
Cabrera High School,1858,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Griffin High School,1468,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Pena High School,962,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Thomas High School,1635,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%
Wilson High School,2283,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,91%

## Bottom Performing Schools (By % Overall Passing)

In [ ]:
# Sort the schools by `% Overall Passing` in ascending order and display the top 5 rows.
bottom_schools = per_school_summary.sort_values(by = '% Overall Passing', ascending= True)
bottom_schools.head(5)

,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,
Figueroa High School,2949,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,53%
Rodriguez High School,3999,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,53%
Ford High School,2739,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,54%
Hernandez High School,4635,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,54%
Huang High School,2917,"$82,932,329,558.00",$629.29,78.985371,81.87784,29370%,33610%,54%

## Math Scores by Grade

In [ ]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by `school_name` and take the mean of the `math_score` column for each.
ninth_grade_math_scores = school_data_complete.groupby('school_name')['math_score'].mean()
tenth_grader_math_scores = school_data_complete.groupby('school_name')['math_score'].mean()
eleventh_grader_math_scores = school_data_complete.groupby('school_name')['math_score'].mean()
twelfth_grader_math_scores = school_data_complete.groupby('school_name')['math_score'].mean()

# Combine each of the scores above into single DataFrame called `math_scores_by_grade`
math_scores_by_grade = {
    '9th': ninth_grade_math_scores,
    '10th': tenth_grader_math_scores,
    '11th': eleventh_grader_math_scores,
    '12th': twelfth_grader_math_scores
}
math_scores_by_grade = pd.DataFrame(math_scores_by_grade)


# Minor data wrangling
math_scores_by_grade.index.name = None

# Display the DataFrame
math_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.048432  77.048432  77.048432  77.048432
Cabrera High School    83.061895  83.061895  83.061895  83.061895
Figueroa High School   76.711767  76.711767  76.711767  76.711767
Ford High School       77.102592  77.102592  77.102592  77.102592
Griffin High School    83.351499  83.351499  83.351499  83.351499
Hernandez High School  77.289752  77.289752  77.289752  77.289752
Holden High School     83.803279  83.803279  83.803279  83.803279
Huang High School      76.629414  76.629414  76.629414  76.629414
Johnson High School    77.072464  77.072464  77.072464  77.072464
Pena High School       83.839917  83.839917  83.839917  83.839917
Rodriguez High School  76.842711  76.842711  76.842711  76.842711
Shelton High School    83.359455  83.359455  83.359455  83.359455
Thomas High School     83.418349  83.418349  83.418349  83.418349
Wilson High School     83.274201  83.274201  83.274201  83.274201
Wright High School     83.682222  83.682222  83.682222  83.682222

## Reading Score by Grade

In [ ]:
# Use the code provided to separate the data by grade
ninth_graders = school_data_complete[(school_data_complete["grade"] == "9th")]
tenth_graders = school_data_complete[(school_data_complete["grade"] == "10th")]
eleventh_graders = school_data_complete[(school_data_complete["grade"] == "11th")]
twelfth_graders = school_data_complete[(school_data_complete["grade"] == "12th")]

# Group by `school_name` and take the mean of the the `reading_score` column for each.
ninth_grade_reading_scores = school_data_complete.groupby('school_name')['reading_score'].mean()
tenth_grader_reading_scores = school_data_complete.groupby('school_name')['reading_score'].mean()
eleventh_grader_reading_scores = school_data_complete.groupby('school_name')['reading_score'].mean()
twelfth_grader_reading_scores = school_data_complete.groupby('school_name')['reading_score'].mean()

# Combine each of the scores above into single DataFrame called `reading_scores_by_grade`
reading_scores_by_grade = {
    '9th' : ninth_grade_reading_scores,
    '10th' : tenth_grader_reading_scores,
    '11th' : eleventh_grader_reading_scores,
    '12th' : twelfth_grader_reading_scores
}
reading_scores_by_grade = pd.DataFrame(reading_scores_by_grade)
# Minor data wrangling
reading_scores_by_grade = reading_scores_by_grade[["9th", "10th", "11th", "12th"]]  #this ensures that the data is in a particular order
reading_scores_by_grade.index.name = None  # this is used to remove the index name especially ehen not important for analysis(school name)

# Display the DataFrame
reading_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     81.033963  81.033963  81.033963  81.033963
Cabrera High School    83.975780  83.975780  83.975780  83.975780
Figueroa High School   81.158020  81.158020  81.158020  81.158020
Ford High School       80.746258  80.746258  80.746258  80.746258
Griffin High School    83.816757  83.816757  83.816757  83.816757
Hernandez High School  80.934412  80.934412  80.934412  80.934412
Holden High School     83.814988  83.814988  83.814988  83.814988
Huang High School      81.182722  81.182722  81.182722  81.182722
Johnson High School    80.966394  80.966394  80.966394  80.966394
Pena High School       84.044699  84.044699  84.044699  84.044699
Rodriguez High School  80.744686  80.744686  80.744686  80.744686
Shelton High School    83.725724  83.725724  83.725724  83.725724
Thomas High School     83.848930  83.848930  83.848930  83.848930
Wilson High School     83.989488  83.989488  83.989488  83.989488
Wright High School     83.955000  83.955000  83.955000  83.955000